### PR TITLE
Fix Pomodoro

### LINKED ISSUE #37: Conditionally Render Back and Next Buttons on Study Page
## Description
Even if there is not a previous/next card, the back and next buttons are rendered.

## Todos

- [ ] Conditionally render back and next buttons based on if there is a previous/next flashcard

## Useful links

- https://github.com/zorazrr/activ-card/blob/cf036f081481e50795d887c11480ed881b6fcffc/src/pages/set/%5Bid%5D.tsx#L92

## Screenshots

Screenshot 2024-02-24 at 3 19 46 AM

### PR DESCRIPTION
**Pull request by Archna-1**
Closes #37, #38, #39

### CODE REVIEW

File: src/pages/set/[id].tsx [hunk 1]
```diff
@@ -86,15 +112,18 @@ const Set = ({ tempIdx }: number | undefined) => {
...
               </button>
               <button
                 onClick={() => setCurIndex(curIndex + 1)}
-                disabled={curIndex === cards.length - 1}
-                className="flex flex-row items-center justify-center p-8"
+                // If the user is at the end or if the user has not attempted to answer the question, disable the next button
+                disabled={
+                  curIndex === cards.length - 1 || maxIndex === curIndex
+                }
+                className={`flex flex-row items-center justify-center p-8 ${curIndex === cards.length - 1 || maxIndex === curIndex ? "invisible" : "visible"}`}
```
Comment (Archna-1) [inline src/pages/set/[id].tsx:126]: Right now, I'm also hiding the button and disabling it. I think the disabled prop is redundant potentially since I changed the behavior of showing these buttons
